# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3-tracing.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3-tracing.yml down`
version: '3.8'

services:
  chrome:
    image: selenium/standalone-chrome
    shm_size: 2gb
    privileged: true
    hostname: chrome
    ports:
       - "4441:4444"
       - "7900:7900"
  firefox:
    image: selenium/standalone-firefox
    shm_size: 2gb
    privileged: true
    hostname: firefox
    ports:
       - "4442:4444"
       - "7901:7900"